### ISSUE TITLE
Latest QMS commit does not compile with GDAL

### ISSUE THREAD

**Issue by anesthesia79** [Maproom/qmapshack#616]
### Describe the bug
Latest QMS 302e3563bd38c308ae3bb9ab3cab8f4733216023 , does not compile with GDAL 3.7.1. 

### What have you done to circle down the problem?
I have also tried to compile with GDAL 3.6.4. Same issue

### To Reproduce
Please check attached error log. 

### Expected behavior
QMS compiles without errors.

### Screenshots
none

### Attachments
`  1%] Linking CXX executable ../../bin/qmapshack
/usr/bin/ld: CMakeFiles/qmapshack.dir/CAbout.cpp.o: in function `CAbout::CAbout(QWidget*)':
/home/emi/Builds/QMapShack/src/qmapshack/CAbout.cpp:40: undefined reference to `GDALVersionInfo'
/usr/bin/ld: CMakeFiles/qmapshack.dir/dem/CDemVRT.cpp.o: in function `CDemVRT::getElevationAt(QPointF const&, bool)':
/home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:140: undefined reference to `GDALDataset::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*)'
/usr/bin/ld: CMakeFiles/qmapshack.dir/dem/CDemVRT.cpp.o: in function `CDemVRT::getSlopeAt(QPointF const&, bool)':
/home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:182: undefined reference to `GDALDataset::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*)'
/usr/bin/ld: CMakeFiles/qmapshack.dir/dem/CDemVRT.cpp.o: in function `CDemVRT::CDemVRT(QString const&, CDemDraw*)':
/home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:35: undefined reference to `GDALOpen'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:42: undefined reference to `GDALDataset::GetRasterCount()'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:43: undefined reference to `GDALClose'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:50: undefined reference to `GDALDataset::GetRasterBand(int)'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:66: undefined reference to `GDALDataset::GetProjectionRef() const'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:75: undefined reference to `GDALDataset::GetRasterXSize()'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:76: undefined reference to `GDALDataset::GetRasterYSize()'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:69: undefined reference to `GDALClose'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:52: undefined reference to `GDALClose'
/usr/bin/ld: CMakeFiles/qmapshack.dir/dem/CDemVRT.cpp.o: in function `CDemVRT::~CDemVRT()':
/home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:116: undefined reference to `GDALClose'
/usr/bin/ld: CMakeFiles/qmapshack.dir/dem/CDemVRT.cpp.o: in function `CDemVRT::drawTile(int, int, int, int, double, double, QPainter&) const':
/home/emi/Builds/QMapShack/src/qmapshack/dem/CDemVRT.cpp:328: undefined reference to `GDALDataset::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*)'
/usr/bin/ld: CMakeFiles/qmapshack.dir/map/CMapVRT.cpp.o: in function `CMapVRT::~CMapVRT()':
/home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:150: undefined reference to `GDALClose'
/usr/bin/ld: CMakeFiles/qmapshack.dir/map/CMapVRT.cpp.o: in function `CMapVRT::testForOverviews(QString const&)':
/home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:222: undefined reference to `GDALDataset::GetRasterCount()'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:223: undefined reference to `GDALDataset::GetRasterBand(int)'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:215: undefined reference to `GDALOpen'
/usr/bin/ld: CMakeFiles/qmapshack.dir/map/CMapVRT.cpp.o: in function `QtSharedPointer::CustomDeleter<GDALDataset, void (*)(void*)>::CustomDeleter(GDALDataset*, void (*)(void*))':
/usr/include/x86_64-linux-gnu/qt5/QtCore/qsharedpointer_impl.h:170: undefined reference to `GDALClose'
/usr/bin/ld: CMakeFiles/qmapshack.dir/map/CMapVRT.cpp.o: in function `CMapVRT::CMapVRT(QString const&, CMapDraw*)':
/home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:38: undefined reference to `GDALOpen'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:47: undefined reference to `GDALDataset::GetRasterCount()'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:91: undefined reference to `GDALDataset::GetRasterCount()'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:104: undefined reference to `GDALDataset::GetProjectionRef() const'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:114: undefined reference to `GDALDataset::GetRasterXSize()'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:115: undefined reference to `GDALDataset::GetRasterYSize()'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:92: undefined reference to `GDALDataset::GetRasterBand(int)'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:49: undefined reference to `GDALDataset::GetRasterBand(int)'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:62: undefined reference to `GDALColorTable::GetColorEntry(int) const'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:61: undefined reference to `GDALColorTable::GetColorEntryCount() const'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:70: undefined reference to `GDALClose'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:52: undefined reference to `GDALClose'
/usr/bin/ld: CMakeFiles/qmapshack.dir/map/CMapVRT.cpp.o: in function `CMapVRT::draw(IDrawContext::buffer_t&)':
/home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:381: undefined reference to `GDALDataset::GetRasterBand(int)'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:386: undefined reference to `GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*)'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:399: undefined reference to `GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*)'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapVRT.cpp:397: undefined reference to `GDALDataset::GetRasterBand(int)'
/usr/bin/ld: CMakeFiles/qmapshack.dir/map/CMapWMTS.cpp.o: in function `CMapWMTS::CMapWMTS(QString const&, CMapDraw*)':
/home/emi/Builds/QMapShack/src/qmapshack/map/CMapWMTS.cpp:198: undefined reference to `OGRSpatialReference::OGRSpatialReference(char const*)'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapWMTS.cpp:202: undefined reference to `OGRSpatialReference::importFromEPSG(int)'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapWMTS.cpp:206: undefined reference to `OGRSpatialReference::exportToWkt(char**) const'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapWMTS.cpp:241: undefined reference to `OGRSpatialReference::~OGRSpatialReference()'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapWMTS.cpp:204: undefined reference to `OGRSpatialReference::importFromURN(char const*)'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapWMTS.cpp:241: undefined reference to `OGRSpatialReference::~OGRSpatialReference()'
/usr/bin/ld: /home/emi/Builds/QMapShack/src/qmapshack/map/CMapWMTS.cpp:241: undefined reference to `OGRSpatialReference::~OGRSpatialReference()'
/usr/bin/ld: CMakeFiles/qmapshack.dir/setup/IAppSetup.cpp.o: in function `IAppSetup::prepareGdal(QString, QString)':
/home/emi/Builds/QMapShack/src/qmapshack/setup/IAppSetup.cpp:55: undefined reference to `GDALAllRegister'
collect2: error: ld returned 1 exit status
make[2]: *** [src/qmapshack/CMakeFiles/qmapshack.dir/build.make:7368: bin/qmapshack] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:182: src/qmapshack/CMakeFiles/qmapshack.dir/all] Fehler 2
make: *** [Makefile:156: all] Fehler 2
emi@emi-GL553VD:~/Builds/build_QMapShack$ 
`

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Linux Mint 21.1
 - QMapShack Version:  302e3563bd38c308ae3bb9ab3cab8f4733216023
 - Window Manager:  Cinnamon

### Additional context
Fur any further questions please contact.

**Comment by kiozen** [comment]
Looks like the linkes does not find the correct library. Please check installation of GDAL (maybe in two locations? /usr and /usr/local ?).  Delete your build path and let camke do it's magic again.

**Comment by anesthesia79** [comment]
@kiozen thanks for pointing out. After cleaning up my mess , everything just works fine. Issue closed.
