### ISSUE TITLE
QMapShack does not compile with Qt-5.15

### ISSUE THREAD

**Issue by grozin** [Maproom/qmapshack#216]
qmapshack-V_1.14.0/src/qmapshack/helpers/CDraw.cpp:210:18: error: aggregate ‘QPainterPath bubblePath’ has incomplete type and cannot be defined

qmapshack-V_1.14.0/src/qmapshack/helpers/CDraw.cpp:240:22: error: aggregate ‘QPainterPath pointerPath’ has incomplete type and cannot be defined

Include files were reorganized in Qt-5.15, and many projects (e..g., qwt) are affected. Some extra #include's are needed. According to https://doc.qt.io/qt-5/qpainterpath.html, to use QPainterPath one has to
`#include <QPainterPath>`
I added this line after the other `#include's` in src/qmapshack/helpers/CDraw.cpp; unfortunately, this did not help. I am not a C++ expert, unfortunately.

By the way, why both qmapshack-1.14.1.tar.gz and qmapshack-1.15.0.tar.gz unpack to qmapshack-V_1.14.0? This is inconvenient.

**Comment by grozin** [comment]
Sorry, this site does not allow to write #include's correctly. I mean
`#include <QPainterPath>`

**Comment by kiozen** [comment]
see also
https://svnweb.freebsd.org/ports?view=revision&revision=536113

**Comment by grozin** [comment]
Thanks, this solves the problem.

**Comment by kiozen** [comment]
Well this was just a mental note for me, what to change. Still, this has to be fixed in the code.
