### PR TITLE
Fix build failure with GDAL 3.13.0.

### PR DESCRIPTION
**Pull request by sebastic**
1.20.1 fails to build with GDAL 3.13.0 due to API changes:
```
error: 'MIN' was not declared in this scope
error: 'MAX' was not declared in this scope
```
See: https://github.com/OSGeo/gdal/commit/1f41ebcb4eaaad8ad5d81a789bf03ce9c20b3beb#diff-5e4656f11ffb922553c3e06f51ce9666886da91cfbc868ba4eac4c7515013c21

### CODE REVIEW

**Comment by kiozen** [comment]
Can you please open a ticket (bug report).  Use comment of this PR as content. Add the ticket number to the commit message (see pattern of other commits) and add the line to the change log (keep order of tickets).  Thx.

**Comment by sebastic** [comment]
I have to test and fix a lot of GDAL reverse dependencies, I don't have time to do all the extra work in your PR workflow.

**Comment by kiozen** [comment]
> I don't have time to do all the extra work in your PR workflow.

This statement holds true for everyone committing to QMapShack. And still the workflow is kept. 

And an incompatibility to a GDAL version is worth to be mentioned and documented properly.

**Comment by sebastic** [comment]
No time to follow the desired workflow.
